### PR TITLE
Remove 'unless/end' pair when parameter list is empty

### PR DESCRIPTION
**Pull request by bim-msft**

### CODE REVIEW

**Review by mmyyrroonn — APPROVED** [review]

**Comment by bim-msft** [comment]
The CI seems stuck, I have no idea how to fix this. Any ideas from top contributors? @olydis @sarangan12 thanks!

**Comment by sarangan12** [comment]
As of February 2021, Azure Resource Management SDK for Ruby and Autorest.Ruby have entered a retirement phase and is no longer officially supported by Microsoft. Here is the complete list of packages that are affected by this. We are committed to making critical security and bug fixes for libraries in this repo until December 31, 2021. After that date, this repo will no longer be maintained.

**Pull request closed without merging**
